FROM php:8.3-fpm
WORKDIR /app1

# Install necessary packages and libraries
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git curl libpng-dev libonig-dev libxml2-dev libzip-dev \
    zip unzip openssl cron nano yaz libyaz-dev \
    iputils-ping libwebp-dev libjpeg-dev libfreetype6-dev \
    libmagickwand-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Install PHP extensions and PECL packages
RUN pecl install --force yaz redis-5.3.3 && \
    docker-php-ext-enable yaz redis && \
    docker-php-ext-configure gd --with-jpeg --with-freetype --with-webp && \
    docker-php-ext-install gd pdo_mysql mysqli mbstring exif pcntl bcmath zip intl gettext calendar

# Install Imagick from a specific commit
ARG IMAGICK_COMMIT="661405abe21d12003207bc8eb0963fafc2c02ee4"
RUN git clone https://github.com/Imagick/imagick /usr/local/src/imagick && \
    cd /usr/local/src/imagick && \
    git checkout ${IMAGICK_COMMIT} && \
    phpize && ./configure && make && make install && \
    docker-php-ext-enable imagick && \
    cd / && rm -rf /usr/local/src/imagick

# Copy Composer from official image
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Update the PHP-FPM listen port using the build argument
RUN echo "listen = 9001" >> /usr/local/etc/php-fpm.d/zz-docker.conf
